[package]
name = "shuttle-rama"
version = "0.49.0"
edition = "2021"
license = "Apache-2.0"
description = "Service implementation to run a rama server on shuttle"
repository = "https://github.com/shuttle-hq/shuttle"
keywords = ["shuttle-service", "rama"]

[dependencies]
rama = { version = "0.2.0-alpha.5", features = ["tcp", "http-full"] }
shuttle-runtime = { path = "../../runtime", version = "0.49.0", default-features = false }

[features]
default = []
